version: 2.1

executors:
  buildpack:
    docker:
      - image: circleci/buildpack-deps:stretch
    working_directory: ~/repo

jobs:
  build-docker-image:
    executor: buildpack
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build docker image
          command: docker build -t gcloud-cli .
      - run:
          name: Check kubectl
          command:  docker run -it gcloud-cli "which" "kubectl"
      - run:
          name: Check gcloud
          command:  docker run -it gcloud-cli "gcloud" "--version"    

  publish-latest-docker-image:
    executor: buildpack
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build docker image
          command: |
            docker build -t "aegirops/gcloud-cli:latest" -t "aegirops/gcloud-cli:${CIRCLE_TAG}" . --no-cache
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push aegirops/gcloud-cli:latest
            docker push aegirops/gcloud-cli:${CIRCLE_TAG}

workflows:
  build-test:
    jobs:
      - build-docker-image:
          filters:
            branches:
              only:
                - /.*/

  publish:
    jobs:  
      - publish-latest-docker-image:
          context: dockerGcloudCli
          filters:
            branches:
              ignore:
                - /.*/
            tags:
              only:
                - /^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}/
